// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy2zTB-uT8QFDFWhxJBqsR3vT0lBZu5CU',
    appId: '1:296676394110:web:b347152bb735719435842f',
    messagingSenderId: '296676394110',
    projectId: 'appdevfinal-6f596',
    authDomain: 'appdevfinal-6f596.firebaseapp.com',
    storageBucket: 'appdevfinal-6f596.appspot.com',
    measurementId: 'G-TZEN4L91QK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlX0DY8p9_Fi88oIS6tUPOdfxUngKrwik',
    appId: '1:296676394110:android:55dadb43c629f61235842f',
    messagingSenderId: '296676394110',
    projectId: 'appdevfinal-6f596',
    storageBucket: 'appdevfinal-6f596.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuk_HegjwCQ3jYTvHjWDiLm8wStU2taXo',
    appId: '1:296676394110:ios:0afa9fd535ec850f35842f',
    messagingSenderId: '296676394110',
    projectId: 'appdevfinal-6f596',
    storageBucket: 'appdevfinal-6f596.appspot.com',
    iosBundleId: 'com.example.appdevfinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuk_HegjwCQ3jYTvHjWDiLm8wStU2taXo',
    appId: '1:296676394110:ios:0afa9fd535ec850f35842f',
    messagingSenderId: '296676394110',
    projectId: 'appdevfinal-6f596',
    storageBucket: 'appdevfinal-6f596.appspot.com',
    iosBundleId: 'com.example.appdevfinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDy2zTB-uT8QFDFWhxJBqsR3vT0lBZu5CU',
    appId: '1:296676394110:web:9408a6fa70f0e36f35842f',
    messagingSenderId: '296676394110',
    projectId: 'appdevfinal-6f596',
    authDomain: 'appdevfinal-6f596.firebaseapp.com',
    storageBucket: 'appdevfinal-6f596.appspot.com',
    measurementId: 'G-0YD9JT3WJT',
  );
}
